export type Song = {
  id: number;
  title: string;
  artist: string;
  album: string;
  duration: string;
  durationSec: number;
  color: string;
  emoji: string;
  genre: string;
  category: "all" | "vpop" | "usuk" | "kpop" | "chill";
  plays: string;
  favorite?: boolean;
  youtubeId?: string;
};

export const SONGS_DATA: Song[] = [
  // --- V-POP HITS (1-30) ---
  {
    id: 1,
    title: "Đừng Làm Trái Tim Anh Đau",
    artist: "Sơn Tùng M-TP",
    album: "Đừng Làm Trái Tim Anh Đau - Single",
    duration: "4:05",
    durationSec: 245,
    color: "linear-gradient(135deg, #ff0844, #ffb199)",
    emoji: "❤️‍🔥",
    genre: "V-Pop",
    category: "vpop",
    plays: "45.2M",
    youtubeId: "abPmZCZZrFA",
    favorite: true,
  },
  {
    id: 2,
    title: "Chúng Ta Của Tương Lai",
    artist: "Sơn Tùng M-TP",
    album: "Chúng Ta - EP",
    duration: "4:12",
    durationSec: 252,
    color: "linear-gradient(135deg, #43e97b, #38f9d7)",
    emoji: "✨",
    genre: "V-Pop",
    category: "vpop",
    plays: "38.6M",
    youtubeId: "zoEtcR5EW08",
    favorite: true,
  },
  {
    id: 3,
    title: "Nấu Ăn Cho Em",
    artist: "Đen ft. PiaLinh",
    album: "Nấu Ăn Cho Em - Single",
    duration: "4:18",
    durationSec: 258,
    color: "linear-gradient(135deg, #fa709a, #fee140)",
    emoji: "🍲",
    genre: "Hip-Hop / Rap",
    category: "vpop",
    plays: "52.1M",
    youtubeId: "ukHK1GVyr0I",
    favorite: true,
  },
  {
    id: 4,
    title: "Từng Là",
    artist: "Vũ Cát Tường",
    album: "Vi Nhất",
    duration: "3:45",
    durationSec: 225,
    color: "linear-gradient(135deg, #667eea, #764ba2)",
    emoji: "🌧️",
    genre: "Ballad",
    category: "vpop",
    plays: "29.4M",
    youtubeId: "i4qZmKSFYvI",
  },
  {
    id: 5,
    title: "Lạ Lùng",
    artist: "Vũ.",
    album: "Một Khung Trời Rực Rỡ",
    duration: "4:20",
    durationSec: 260,
    color: "linear-gradient(135deg, #2b5876, #4e4376)",
    emoji: "🍂",
    genre: "Indie Pop",
    category: "vpop",
    plays: "60.5M",
    youtubeId: "F5tS5m86bOI",
    favorite: true,
  },
  {
    id: 6,
    title: "Bình Yên",
    artist: "Vũ. ft. Binz",
    album: "Bảo Tàng Của Nuối Tiếc",
    duration: "3:58",
    durationSec: 238,
    color: "linear-gradient(135deg, #0ba360, #3cba92)",
    emoji: "🍃",
    genre: "Indie / Rap",
    category: "vpop",
    plays: "18.3M",
    youtubeId: "5PWkbxuf7jc",
  },
  {
    id: 7,
    title: "Cắt Đôi Nỗi Sầu",
    artist: "Tăng Duy Tân",
    album: "Cắt Đôi Nỗi Sầu - Single",
    duration: "3:10",
    durationSec: 190,
    color: "linear-gradient(135deg, #f857a6, #ff5858)",
    emoji: "💔",
    genre: "Dance / Electronic",
    category: "vpop",
    plays: "44.8M",
    youtubeId: "GpmOn4RyzZI",
  },
  {
    id: 8,
    title: "Không Thể Say",
    artist: "HIEUTHUHAI",
    album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
    duration: "3:32",
    durationSec: 212,
    color: "linear-gradient(135deg, #30cfd0, #330867)",
    emoji: "🥂",
    genre: "Hip-Hop / Rap",
    category: "vpop",
    plays: "31.7M",
    youtubeId: "d6pgocXnK8U",
    favorite: true,
  },
  {
    id: 9,
    title: "Giờ Thì Ai Cười",
    artist: "HIEUTHUHAI",
    album: "Ai Cũng Phải Bắt Đầu Từ Đâu Đó",
    duration: "3:25",
    durationSec: 205,
    color: "linear-gradient(135deg, #f12711, #f5af19)",
    emoji: "🔥",
    genre: "Hip-Hop / Rap",
    category: "vpop",
    plays: "22.5M",
    youtubeId: "R6p6c-feIqw",
  },
  {
    id: 10,
    title: "Nếu Lúc Đó",
    artist: "tlinh ft. 2pillz",
    album: "ái",
    duration: "4:02",
    durationSec: 242,
    color: "linear-gradient(135deg, #a18cd1, #fbc2eb)",
    emoji: "🌸",
    genre: "R&B / Soul",
    category: "vpop",
    plays: "48.9M",
    youtubeId: "fyMgBQioTLo",
    favorite: true,
  },
  {
    id: 11,
    title: "Ghé Qua",
    artist: "Dick, Tofu, PC",
    album: "Bạn Có Khoẻ Không?",
    duration: "4:32",
    durationSec: 272,
    color: "linear-gradient(135deg, #48c6ef, #6f86d6)",
    emoji: "☕️",
    genre: "Rap / Hip-Hop",
    category: "vpop",
    plays: "35.1M",
    youtubeId: "W2FRMzCuPzY",
  },
  {
    id: 12,
    title: "See Tình",
    artist: "Hoàng Thùy Linh",
    album: "LINK",
    duration: "3:05",
    durationSec: 185,
    color: "linear-gradient(135deg, #ff758c, #ff7eb3)",
    emoji: "💃",
    genre: "Dance-Pop",
    category: "vpop",
    plays: "88.4M",
    youtubeId: "UfMEtjxzpBk",
    favorite: true,
  },
  {
    id: 13,
    title: "Bo Sắc Bo",
    artist: "Hoàng Thùy Linh",
    album: "LINK",
    duration: "3:20",
    durationSec: 200,
    color: "linear-gradient(135deg, #b224ef, #7579ff)",
    emoji: "🎭",
    genre: "Folk Pop",
    category: "vpop",
    plays: "26.3M",
    youtubeId: "LxNzRN8EMcw",
  },
  {
    id: 14,
    title: "Waiting For You",
    artist: "MONO ft. Onionn",
    album: "22",
    duration: "4:15",
    durationSec: 255,
    color: "linear-gradient(135deg, #00c6ff, #0072ff)",
    emoji: "🕺",
    genre: "Synthwave / Pop",
    category: "vpop",
    plays: "72.0M",
    youtubeId: "okz5RIZRT0U",
    favorite: true,
  },
  {
    id: 15,
    title: "Em Là",
    artist: "MONO",
    album: "22",
    duration: "3:18",
    durationSec: 198,
    color: "linear-gradient(135deg, #f83600, #f9d423)",
    emoji: "⚡️",
    genre: "Pop",
    category: "vpop",
    plays: "19.8M",
    youtubeId: "bpOwZ68fcQE",
  },
  {
    id: 16,
    title: "Từng Ngày Yêu",
    artist: "Wren Evans",
    album: "Loi Choi",
    duration: "3:08",
    durationSec: 188,
    color: "linear-gradient(135deg, #ff416c, #ff4b2b)",
    emoji: "🎸",
    genre: "Indie Pop",
    category: "vpop",
    plays: "28.1M",
    youtubeId: "f-VsoLm4i5c",
  },
  {
    id: 17,
    title: "Bé Ơi Từ Từ",
    artist: "Wren Evans",
    album: "Loi Choi",
    duration: "3:22",
    durationSec: 202,
    color: "linear-gradient(135deg, #11998e, #38ef7d)",
    emoji: "🏎️",
    genre: "Drill / Pop",
    category: "vpop",
    plays: "24.6M",
    youtubeId: "onM02bB0mYw",
  },
  {
    id: 18,
    title: "Mascara",
    artist: "Chillies",
    album: "Qua Khung Cửa Sổ",
    duration: "3:58",
    durationSec: 238,
    color: "linear-gradient(135deg, #3a1c71, #d76d77)",
    emoji: "💄",
    genre: "Pop Rock",
    category: "vpop",
    plays: "42.0M",
    youtubeId: "ntEoGvhoVac",
    favorite: true,
  },
  {
    id: 19,
    title: "Vùng Ký Ức",
    artist: "Chillies",
    album: "Qua Khung Cửa Sổ",
    duration: "4:40",
    durationSec: 280,
    color: "linear-gradient(135deg, #1f4037, #99f2c8)",
    emoji: "🌌",
    genre: "Indie Rock",
    category: "vpop",
    plays: "36.5M",
    youtubeId: "T0sHaz4H9MQ",
  },
  {
    id: 20,
    title: "vaicaunoicokhiennguoithaydoi",
    artist: "GREY D ft. tlinh",
    album: "Dự Báo Thời Tiết Hôm Nay Mưa",
    duration: "3:40",
    durationSec: 220,
    color: "linear-gradient(135deg, #4e54c8, #8f94fb)",
    emoji: "☔️",
    genre: "R&B",
    category: "vpop",
    plays: "33.2M",
    youtubeId: "2iidlwQ-NfU",
  },
  {
    id: 21,
    title: "đưa em về nhàa",
    artist: "GREY D ft. Chillies",
    album: "Dự Báo Thời Tiết Hôm Nay Mưa",
    duration: "3:30",
    durationSec: 210,
    color: "linear-gradient(135deg, #f77062, #fe5196)",
    emoji: "🛵",
    genre: "Acoustic Pop",
    category: "vpop",
    plays: "27.4M",
    youtubeId: "YM5nx2s8cz0",
  },
  {
    id: 22,
    title: "Ngày Đầu Tiên",
    artist: "Đức Phúc",
    album: "Ngày Đầu Tiên - Single",
    duration: "3:35",
    durationSec: 215,
    color: "linear-gradient(135deg, #f093fb, #f5576c)",
    emoji: "💍",
    genre: "Ballad",
    category: "vpop",
    plays: "50.1M",
    youtubeId: "R6aQJWWWTy4",
  },
  {
    id: 23,
    title: "Có Không Giữ Mất Đừng Tìm",
    artist: "Trúc Nhân",
    album: "Có Không Giữ Mất Đừng Tìm",
    duration: "3:48",
    durationSec: 228,
    color: "linear-gradient(135deg, #fa709a, #fee140)",
    emoji: "🎪",
    genre: "Pop / Disco",
    category: "vpop",
    plays: "39.7M",
    youtubeId: "e-1JJNmb-3o",
  },
  {
    id: 24,
    title: "Ưng Quá Chừng",
    artist: "AMEE",
    album: "Ưng Quá Chừng - Single",
    duration: "2:36",
    durationSec: 156,
    color: "linear-gradient(135deg, #ff9a9e, #fecfef)",
    emoji: "🐱",
    genre: "Teen Pop",
    category: "vpop",
    plays: "34.0M",
    youtubeId: "4qNALNWoGmI",
  },
  {
    id: 25,
    title: "Chân Ái",
    artist: "Orange ft. Khói",
    album: "Chân Ái - Single",
    duration: "3:52",
    durationSec: 232,
    color: "linear-gradient(135deg, #6a11cb, #2575fc)",
    emoji: "🏮",
    genre: "R&B / World",
    category: "vpop",
    plays: "30.8M",
    youtubeId: "i9_ZpPDtBCA",
  },
  {
    id: 26,
    title: "Ánh Sao Và Bầu Trời",
    artist: "T.R.I",
    album: "Ánh Sao Và Bầu Trời - Single",
    duration: "4:10",
    durationSec: 250,
    color: "linear-gradient(135deg, #09203f, #537895)",
    emoji: "⭐️",
    genre: "Indie Pop",
    category: "vpop",
    plays: "25.9M",
    youtubeId: "9vaLkYElidg",
  },
  {
    id: 27,
    title: "Bước Qua Mùa Cô Đơn",
    artist: "Vũ.",
    album: "Một Khung Trời Rực Rỡ",
    duration: "4:38",
    durationSec: 278,
    color: "linear-gradient(135deg, #13547a, #80d0c7)",
    emoji: "❄️",
    genre: "Indie Pop",
    category: "vpop",
    plays: "41.6M",
    youtubeId: "n6Pnzi6r9NU",
  },
  {
    id: 28,
    title: "Tháng Tư Là Lời Nói Dối Của Em",
    artist: "Hà Anh Tuấn",
    album: "Fragile",
    duration: "4:45",
    durationSec: 285,
    color: "linear-gradient(135deg, #ffecd2, #fcb69f)",
    emoji: "🌸",
    genre: "Acoustic Ballad",
    category: "vpop",
    plays: "65.0M",
    youtubeId: "kdLfaZPrIHY",
  },
  {
    id: 29,
    title: "Xuân Thì",
    artist: "Hà Anh Tuấn",
    album: "Truyện Ngắn",
    duration: "4:22",
    durationSec: 262,
    color: "linear-gradient(135deg, #d299c2, #fef9d7)",
    emoji: "🎋",
    genre: "Ballad",
    category: "vpop",
    plays: "21.4M",
    youtubeId: "yoQXAyxLj0Q",
  },
  {
    id: 30,
    title: "Trốn Tìm",
    artist: "Đen ft. MTV Band",
    album: "Trốn Tìm - Single",
    duration: "4:09",
    durationSec: 249,
    color: "linear-gradient(135deg, #89f7fe, #66a6ff)",
    emoji: "🌲",
    genre: "Rap / Acoustic",
    category: "vpop",
    plays: "49.3M",
    youtubeId: "Ws-QlpSltr8",
  },

  // --- US-UK GLOBAL HITS (31-65) ---
  {
    id: 31,
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    duration: "3:20",
    durationSec: 200,
    color: "linear-gradient(135deg, #e52d27, #b31217)",
    emoji: "🕶️",
    genre: "Synth-Pop",
    category: "usuk",
    plays: "140.5M",
    youtubeId: "fHI8X4OXluQ",
    favorite: true,
  },
  {
    id: 32,
    title: "Starboy",
    artist: "The Weeknd ft. Daft Punk",
    album: "Starboy",
    duration: "3:50",
    durationSec: 230,
    color: "linear-gradient(135deg, #1d2671, #c33764)",
    emoji: "⚡️",
    genre: "R&B / Electropop",
    category: "usuk",
    plays: "115.8M",
    youtubeId: "Rif-RTvmmss",
  },
  {
    id: 33,
    title: "Cruel Summer",
    artist: "Taylor Swift",
    album: "Lover",
    duration: "2:58",
    durationSec: 178,
    color: "linear-gradient(135deg, #fbc2eb, #a6c1ee)",
    emoji: "☀️",
    genre: "Pop",
    category: "usuk",
    plays: "128.2M",
    youtubeId: "ic8j13piAhQ",
    favorite: true,
  },
  {
    id: 34,
    title: "Anti-Hero",
    artist: "Taylor Swift",
    album: "Midnights",
    duration: "3:20",
    durationSec: 200,
    color: "linear-gradient(135deg, #0f2027, #203a43, #2c5364)",
    emoji: "🕰️",
    genre: "Synth-Pop",
    category: "usuk",
    plays: "95.6M",
    youtubeId: "XqN2qFvY64U",
  },
  {
    id: 35,
    title: "Fortnight",
    artist: "Taylor Swift ft. Post Malone",
    album: "THE TORTURED POETS DEPARTMENT",
    duration: "3:48",
    durationSec: 228,
    color: "linear-gradient(135deg, #434343, #000000)",
    emoji: "📜",
    genre: "Down-Tempo Pop",
    category: "usuk",
    plays: "76.4M",
    youtubeId: "b7kmP1fsGg8",
  },
  {
    id: 36,
    title: "BIRDS OF A FEATHER",
    artist: "Billie Eilish",
    album: "HIT ME HARD AND SOFT",
    duration: "3:16",
    durationSec: 196,
    color: "linear-gradient(135deg, #0052d4, #4364f7, #6fb1fc)",
    emoji: "🪶",
    genre: "Alt-Pop",
    category: "usuk",
    plays: "82.1M",
    youtubeId: "d5gf9dXbPi0",
    favorite: true,
  },
  {
    id: 37,
    title: "bad guy",
    artist: "Billie Eilish",
    album: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    duration: "3:14",
    durationSec: 194,
    color: "linear-gradient(135deg, #11998e, #38ef7d)",
    emoji: "😈",
    genre: "Electropop",
    category: "usuk",
    plays: "110.3M",
    youtubeId: "DyDfgMOUjCI",
  },
  {
    id: 38,
    title: "Die With A Smile",
    artist: "Lady Gaga & Bruno Mars",
    album: "Die With A Smile - Single",
    duration: "4:11",
    durationSec: 251,
    color: "linear-gradient(135deg, #ff416c, #ff4b2b)",
    emoji: "🌹",
    genre: "Pop / Soul",
    category: "usuk",
    plays: "71.9M",
    youtubeId: "PfH7jq_uSCM",
    favorite: true,
  },
  {
    id: 39,
    title: "Leave The Door Open",
    artist: "Bruno Mars, Anderson .Paak, Silk Sonic",
    album: "An Evening With Silk Sonic",
    duration: "4:02",
    durationSec: 242,
    color: "linear-gradient(135deg, #b79891, #94716b)",
    emoji: "🚪",
    genre: "Soul / R&B",
    category: "usuk",
    plays: "68.4M",
    youtubeId: "adLGHcj_fmA",
  },
  {
    id: 40,
    title: "As It Was",
    artist: "Harry Styles",
    album: "Harry's House",
    duration: "2:47",
    durationSec: 167,
    color: "linear-gradient(135deg, #f7971e, #ffd200)",
    emoji: "🏠",
    genre: "Synth-Pop",
    category: "usuk",
    plays: "135.0M",
    youtubeId: "CjIUVRei27g",
    favorite: true,
  },
  {
    id: 41,
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    album: "Fine Line",
    duration: "2:54",
    durationSec: 174,
    color: "linear-gradient(135deg, #ff512f, #dd2476)",
    emoji: "🍉",
    genre: "Funk Pop",
    category: "usuk",
    plays: "105.7M",
    youtubeId: "7-x3uD5z1bQ",
  },
  {
    id: 42,
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:23",
    durationSec: 203,
    color: "linear-gradient(135deg, #8a2387, #e94057, #f27121)",
    emoji: "✨",
    genre: "Nu-Disco",
    category: "usuk",
    plays: "118.9M",
    youtubeId: "WHuBW3qKm9g",
  },
  {
    id: 43,
    title: "Dance The Night",
    artist: "Dua Lipa",
    album: "Barbie The Album",
    duration: "2:56",
    durationSec: 176,
    color: "linear-gradient(135deg, #f093fb, #f5576c)",
    emoji: "💖",
    genre: "Disco-Pop",
    category: "usuk",
    plays: "58.4M",
    youtubeId: "hCLkVrp_4CE",
  },
  {
    id: 44,
    title: "vampire",
    artist: "Olivia Rodrigo",
    album: "GUTS",
    duration: "3:39",
    durationSec: 219,
    color: "linear-gradient(135deg, #4b1248, #f0c27b)",
    emoji: "🩸",
    genre: "Pop Rock",
    category: "usuk",
    plays: "74.8M",
    youtubeId: "Fqey8LxQxFU",
  },
  {
    id: 45,
    title: "drivers license",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    duration: "4:02",
    durationSec: 242,
    color: "linear-gradient(135deg, #654ea3, #eaafc8)",
    emoji: "🚗",
    genre: "Power Pop",
    category: "usuk",
    plays: "99.1M",
    youtubeId: "2PRvp-mP_q0",
  },
  {
    id: 46,
    title: "Circles",
    artist: "Post Malone",
    album: "Hollywood's Bleeding",
    duration: "3:35",
    durationSec: 215,
    color: "linear-gradient(135deg, #3f2b96, #a8c0ff)",
    emoji: "🔄",
    genre: "Pop Rock",
    category: "usuk",
    plays: "112.5M",
    youtubeId: "pQV0WEdT_OE",
  },
  {
    id: 47,
    title: "Sunflower",
    artist: "Post Malone & Swae Lee",
    album: "Spider-Man: Into the Spider-Verse",
    duration: "2:38",
    durationSec: 158,
    color: "linear-gradient(135deg, #fce38a, #f38181)",
    emoji: "🌻",
    genre: "Hip-Hop / Pop",
    category: "usuk",
    plays: "130.2M",
    youtubeId: "ApXoWvfEYVU",
    favorite: true,
  },
  {
    id: 48,
    title: "Not Like Us",
    artist: "Kendrick Lamar",
    album: "Not Like Us - Single",
    duration: "4:34",
    durationSec: 274,
    color: "linear-gradient(135deg, #000428, #004e92)",
    emoji: "👑",
    genre: "West Coast Hip-Hop",
    category: "usuk",
    plays: "65.3M",
    youtubeId: "T6eK-2OQtew",
    favorite: true,
  },
  {
    id: 49,
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    album: "DAMN.",
    duration: "2:57",
    durationSec: 177,
    color: "linear-gradient(135deg, #eb3349, #f45c43)",
    emoji: "🔥",
    genre: "Hip-Hop",
    category: "usuk",
    plays: "98.7M",
    youtubeId: "wL_xmuij6lA",
  },
  {
    id: 50,
    title: "Kill Bill",
    artist: "SZA",
    album: "SOS",
    duration: "2:33",
    durationSec: 153,
    color: "linear-gradient(135deg, #134e5e, #71b280)",
    emoji: "⚔️",
    genre: "R&B",
    category: "usuk",
    plays: "89.4M",
    youtubeId: "SQnc1QibapQ",
  },
  {
    id: 51,
    title: "Snooze",
    artist: "SZA",
    album: "SOS",
    duration: "3:21",
    durationSec: 201,
    color: "linear-gradient(135deg, #f857a6, #ff5858)",
    emoji: "💤",
    genre: "Contemporary R&B",
    category: "usuk",
    plays: "78.2M",
    youtubeId: "Sv5yCzPCkv8",
  },
  {
    id: 52,
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    duration: "3:53",
    durationSec: 233,
    color: "linear-gradient(135deg, #00c6ff, #0072ff)",
    emoji: "🔷",
    genre: "Pop",
    category: "usuk",
    plays: "155.0M",
    youtubeId: "_dK2tDK9grQ",
  },
  {
    id: 53,
    title: "Perfect",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    duration: "4:23",
    durationSec: 263,
    color: "linear-gradient(135deg, #ff9966, #ff5e62)",
    emoji: "✨",
    genre: "Romantic Ballad",
    category: "usuk",
    plays: "122.4M",
    youtubeId: "2Vv-BfVoq4g",
  },
  {
    id: 54,
    title: "Easy On Me",
    artist: "Adele",
    album: "30",
    duration: "3:44",
    durationSec: 224,
    color: "linear-gradient(135deg, #485563, #29323c)",
    emoji: "🍂",
    genre: "Soul Pop",
    category: "usuk",
    plays: "84.3M",
    youtubeId: "X-yIEMduRXk",
  },
  {
    id: 55,
    title: "Rolling in the Deep",
    artist: "Adele",
    album: "21",
    duration: "3:48",
    durationSec: 228,
    color: "linear-gradient(135deg, #3a1c71, #d76d77, #ffaf7b)",
    emoji: "🌊",
    genre: "Blues / Soul",
    category: "usuk",
    plays: "119.0M",
    youtubeId: "bDtjO-R0QSo",
  },
  {
    id: 56,
    title: "Yellow",
    artist: "Coldplay",
    album: "Parachutes",
    duration: "4:29",
    durationSec: 269,
    color: "linear-gradient(135deg, #ffe000, #799f0c)",
    emoji: "💛",
    genre: "Alt-Rock",
    category: "usuk",
    plays: "108.6M",
    youtubeId: "tdVAqxNLXiw",
    favorite: true,
  },
  {
    id: 57,
    title: "Viva La Vida",
    artist: "Coldplay",
    album: "Viva La Vida or Death and All His Friends",
    duration: "4:02",
    durationSec: 242,
    color: "linear-gradient(135deg, #cc2b5e, #753a88)",
    emoji: "👑",
    genre: "Baroque Pop",
    category: "usuk",
    plays: "95.1M",
    youtubeId: "dvgZkm1xWPE",
  },
  {
    id: 58,
    title: "God's Plan",
    artist: "Drake",
    album: "Scorpion",
    duration: "3:18",
    durationSec: 198,
    color: "linear-gradient(135deg, #2c3e50, #3498db)",
    emoji: "🙏",
    genre: "Trap / Pop Rap",
    category: "usuk",
    plays: "114.7M",
    youtubeId: "m1a_GqJf02M",
  },
  {
    id: 59,
    title: "One Dance",
    artist: "Drake ft. Wizkid & Kyla",
    album: "Views",
    duration: "2:53",
    durationSec: 173,
    color: "linear-gradient(135deg, #ff7e5f, #feb47b)",
    emoji: "💃",
    genre: "Afrobeats",
    category: "usuk",
    plays: "102.3M",
    youtubeId: "FOqKN-ouAUE",
  },
  {
    id: 60,
    title: "Stay",
    artist: "The Kid LAROI & Justin Bieber",
    album: "F*CK LOVE 3: OVER YOU",
    duration: "2:21",
    durationSec: 141,
    color: "linear-gradient(135deg, #fd746c, #ff9068)",
    emoji: "⚡️",
    genre: "Pop Punk / Synth",
    category: "usuk",
    plays: "125.6M",
    youtubeId: "Qb8q4ijHk_M",
  },
  {
    id: 61,
    title: "Ghost",
    artist: "Justin Bieber",
    album: "Justice",
    duration: "2:33",
    durationSec: 153,
    color: "linear-gradient(135deg, #1d976c, #93f9b9)",
    emoji: "👻",
    genre: "Pop",
    category: "usuk",
    plays: "73.2M",
    youtubeId: "KRUWn3dLoRg",
  },
  {
    id: 62,
    title: "Believer",
    artist: "Imagine Dragons",
    album: "Evolve",
    duration: "3:24",
    durationSec: 204,
    color: "linear-gradient(135deg, #e65c00, #f9d423)",
    emoji: "⚡️",
    genre: "Arena Rock",
    category: "usuk",
    plays: "132.8M",
    youtubeId: "IhP3J0j9JmY",
  },
  {
    id: 63,
    title: "Demons",
    artist: "Imagine Dragons",
    album: "Night Visions",
    duration: "2:57",
    durationSec: 177,
    color: "linear-gradient(135deg, #4b6cb7, #182848)",
    emoji: "🌘",
    genre: "Indie Rock",
    category: "usuk",
    plays: "94.5M",
    youtubeId: "pvrkfb1C4tE",
  },
  {
    id: 64,
    title: "Counting Stars",
    artist: "OneRepublic",
    album: "Native",
    duration: "4:17",
    durationSec: 257,
    color: "linear-gradient(135deg, #614385, #516395)",
    emoji: "⭐",
    genre: "Pop Rock",
    category: "usuk",
    plays: "120.4M",
    youtubeId: "4Afc3DyirHM",
  },
  {
    id: 65,
    title: "Wake Me Up",
    artist: "Avicii",
    album: "True",
    duration: "4:07",
    durationSec: 247,
    color: "linear-gradient(135deg, #ffb347, #ffcc33)",
    emoji: "🌅",
    genre: "EDM / Folktronica",
    category: "usuk",
    plays: "115.0M",
    youtubeId: "5y_KJAg8bHI",
    favorite: true,
  },

  // --- K-POP & ASIAN POP HITS (66-85) ---
  {
    id: 66,
    title: "Seven",
    artist: "Jung Kook ft. Latto",
    album: "GOLDEN",
    duration: "3:04",
    durationSec: 184,
    color: "linear-gradient(135deg, #ff0844, #ffb199)",
    emoji: "🗓️",
    genre: "UK Garage Pop",
    category: "kpop",
    plays: "88.9M",
    youtubeId: "Vs64cZbeY88",
    favorite: true,
  },
  {
    id: 67,
    title: "Dynamite",
    artist: "BTS",
    album: "BE",
    duration: "3:19",
    durationSec: 199,
    color: "linear-gradient(135deg, #fa709a, #fee140)",
    emoji: "🧨",
    genre: "Disco-Pop",
    category: "kpop",
    plays: "110.2M",
    youtubeId: "OiMWFojB9Ok",
  },
  {
    id: 68,
    title: "Butter",
    artist: "BTS",
    album: "Butter - Single",
    duration: "2:44",
    durationSec: 164,
    color: "linear-gradient(135deg, #ffe000, #799f0c)",
    emoji: "🧈",
    genre: "Dance-Pop",
    category: "kpop",
    plays: "95.0M",
    youtubeId: "WMweEpGlu_U",
  },
  {
    id: 69,
    title: "How You Like That",
    artist: "BLACKPINK",
    album: "THE ALBUM",
    duration: "3:00",
    durationSec: 180,
    color: "linear-gradient(135deg, #ff758c, #ff7eb3)",
    emoji: "👑",
    genre: "EDM / Hip-Hop",
    category: "kpop",
    plays: "96.4M",
    youtubeId: "VFo2Y_DqGTk",
    favorite: true,
  },
  {
    id: 70,
    title: "Pink Venom",
    artist: "BLACKPINK",
    album: "BORN PINK",
    duration: "3:06",
    durationSec: 186,
    color: "linear-gradient(135deg, #ec008c, #fc6767)",
    emoji: "🕷️",
    genre: "Hip-Hop",
    category: "kpop",
    plays: "84.1M",
    youtubeId: "3or3dp3qNQU",
  },
  {
    id: 71,
    title: "Hype Boy",
    artist: "NewJeans",
    album: "New Jeans 1st EP",
    duration: "2:59",
    durationSec: 179,
    color: "linear-gradient(135deg, #00c6ff, #0072ff)",
    emoji: "👖",
    genre: "R&B / Pop",
    category: "kpop",
    plays: "82.5M",
    youtubeId: "T--6HBX2K4g",
    favorite: true,
  },
  {
    id: 72,
    title: "Super Shy",
    artist: "NewJeans",
    album: "Get Up - EP",
    duration: "2:34",
    durationSec: 154,
    color: "linear-gradient(135deg, #a18cd1, #fbc2eb)",
    emoji: "🙈",
    genre: "Bubblegum Drum & Bass",
    category: "kpop",
    plays: "76.0M",
    youtubeId: "n7ePZLn9_lQ",
  },
  {
    id: 73,
    title: "Ditto",
    artist: "NewJeans",
    album: "OMG",
    duration: "3:06",
    durationSec: 186,
    color: "linear-gradient(135deg, #667eea, #764ba2)",
    emoji: "📼",
    genre: "Baltimore Club",
    category: "kpop",
    plays: "89.2M",
    youtubeId: "5emU4TSPxc8",
    favorite: true,
  },
  {
    id: 74,
    title: "Magnetic",
    artist: "ILLIT",
    album: "SUPER REAL ME",
    duration: "2:40",
    durationSec: 160,
    color: "linear-gradient(135deg, #ff9a9e, #fecfef)",
    emoji: "🧲",
    genre: "Plugg / Hyperpop",
    category: "kpop",
    plays: "68.3M",
    youtubeId: "YVMUjAE-0SM",
  },
  {
    id: 75,
    title: "Perfect Night",
    artist: "LE SSERAFIM",
    album: "Perfect Night - Single",
    duration: "2:39",
    durationSec: 159,
    color: "linear-gradient(135deg, #30cfd0, #330867)",
    emoji: "🌙",
    genre: "2-Step Garage",
    category: "kpop",
    plays: "61.7M",
    youtubeId: "hLvWy2b857I",
  },
  {
    id: 76,
    title: "EASY",
    artist: "LE SSERAFIM",
    album: "EASY",
    duration: "2:45",
    durationSec: 165,
    color: "linear-gradient(135deg, #f12711, #f5af19)",
    emoji: "🐆",
    genre: "Old School Hip-Hop",
    category: "kpop",
    plays: "52.0M",
    youtubeId: "eAdqhLFmHa8",
  },
  {
    id: 77,
    title: "Supernova",
    artist: "aespa",
    album: "Armageddon - The 1st Album",
    duration: "2:58",
    durationSec: 178,
    color: "linear-gradient(135deg, #8a2387, #e94057, #f27121)",
    emoji: "💥",
    genre: "Hyperpop / Dance",
    category: "kpop",
    plays: "64.9M",
    youtubeId: "vQkdt5txAcM",
    favorite: true,
  },
  {
    id: 78,
    title: "Next Level",
    artist: "aespa",
    album: "Next Level - Single",
    duration: "3:41",
    durationSec: 221,
    color: "linear-gradient(135deg, #43e97b, #38f9d7)",
    emoji: "🛸",
    genre: "Hip-Hop Dance",
    category: "kpop",
    plays: "71.4M",
    youtubeId: "4TWR90KJl84",
  },
  {
    id: 79,
    title: "Cupid",
    artist: "FIFTY FIFTY",
    album: "The Beginning: Cupid",
    duration: "2:54",
    durationSec: 174,
    color: "linear-gradient(135deg, #ffecd2, #fcb69f)",
    emoji: "💘",
    genre: "Disco-Pop",
    category: "kpop",
    plays: "91.8M",
    youtubeId: "6uvUTu716rU",
  },
  {
    id: 80,
    title: "Love Lee",
    artist: "AKMU",
    album: "Love Lee - Single",
    duration: "2:59",
    durationSec: 179,
    color: "linear-gradient(135deg, #a8edea, #fed6e3)",
    emoji: "🥰",
    genre: "Acoustic Pop",
    category: "kpop",
    plays: "44.0M",
    youtubeId: "XBVauz0iN8c",
  },
  {
    id: 81,
    title: "Gurenge (紅蓮華)",
    artist: "LiSA",
    album: "LEO-NiNE",
    duration: "3:58",
    durationSec: 238,
    color: "linear-gradient(135deg, #ff0844, #b31217)",
    emoji: "⚔️",
    genre: "J-Rock",
    category: "kpop",
    plays: "78.2M",
    youtubeId: "x1FV6IrjZCY",
  },
  {
    id: 82,
    title: "Yoru ni Kakeru (夜に駆ける)",
    artist: "YOASOBI",
    album: "THE BOOK",
    duration: "4:21",
    durationSec: 261,
    color: "linear-gradient(135deg, #09203f, #537895)",
    emoji: "🌃",
    genre: "J-Pop",
    category: "kpop",
    plays: "98.5M",
    youtubeId: "by4SYYWlhEs",
    favorite: true,
  },
  {
    id: 83,
    title: "Idol (アイドル)",
    artist: "YOASOBI",
    album: "Idol - Single",
    duration: "3:33",
    durationSec: 213,
    color: "linear-gradient(135deg, #f857a6, #ff5858)",
    emoji: "🌟",
    genre: "J-Pop",
    category: "kpop",
    plays: "112.0M",
    youtubeId: "ZRtdQ81jPUQ",
    favorite: true,
  },
  {
    id: 84,
    title: "Shinunoga E-Wa (死ぬのがいいわ)",
    artist: "Fujii Kaze",
    album: "HELP EVER HURT NEVER",
    duration: "3:05",
    durationSec: 185,
    color: "linear-gradient(135deg, #1e3c72, #2a5298)",
    emoji: "🍃",
    genre: "J-R&B",
    category: "kpop",
    plays: "80.4M",
    youtubeId: "dawrQnvwMTY",
  },
  {
    id: 85,
    title: "Matsuri (まつり)",
    artist: "Fujii Kaze",
    album: "LOVE ALL SERVE ALL",
    duration: "3:46",
    durationSec: 226,
    color: "linear-gradient(135deg, #ff7e5f, #feb47b)",
    emoji: "🏮",
    genre: "Urban Pop",
    category: "kpop",
    plays: "46.2M",
    youtubeId: "NwOvu-j_WjY",
  },

  // --- CHILL, LO-FI & AMBIENT (86-100) ---
  {
    id: 86,
    title: "Lofi Rain in Tokyo",
    artist: "ChilledCow",
    album: "Midnight Sessions Vol. 1",
    duration: "2:45",
    durationSec: 165,
    color: "linear-gradient(135deg, #2c3e50, #4ca1af)",
    emoji: "🌧️",
    genre: "Lo-Fi Hip-Hop",
    category: "chill",
    plays: "32.4M",
    youtubeId: "XKDGZ-VWLMg",
    favorite: true,
  },
  {
    id: 87,
    title: "Coffee Shop Acoustics",
    artist: "Kudasaibeats",
    album: "Falling In Love",
    duration: "2:20",
    durationSec: 140,
    color: "linear-gradient(135deg, #c31432, #240b36)",
    emoji: "☕️",
    genre: "Lo-Fi Beats",
    category: "chill",
    plays: "28.1M",
    youtubeId: "BywDOO99Ia0",
  },
  {
    id: 88,
    title: "Sunflower Dreaming",
    artist: "Idealism",
    album: "Rainy Evening",
    duration: "2:35",
    durationSec: 155,
    color: "linear-gradient(135deg, #f7971e, #ffd200)",
    emoji: "🌻",
    genre: "Chillhop",
    category: "chill",
    plays: "19.5M",
    youtubeId: "iV2UJPwueEk",
  },
  {
    id: 89,
    title: "Warm Summer Breeze",
    artist: "Jinsang",
    album: "Solitude",
    duration: "2:15",
    durationSec: 135,
    color: "linear-gradient(135deg, #ff9a9e, #fecfef)",
    emoji: "🍃",
    genre: "Lo-Fi Hip-Hop",
    category: "chill",
    plays: "24.0M",
    youtubeId: "GQQbjpomexo",
  },
  {
    id: 90,
    title: "Night Sky Reflection",
    artist: "Kupla",
    album: "Kingdom in Blue",
    duration: "3:10",
    durationSec: 190,
    color: "linear-gradient(135deg, #0f2027, #2c5364)",
    emoji: "🌌",
    genre: "Ambient Beats",
    category: "chill",
    plays: "17.6M",
    youtubeId: "202-typrZhA",
  },
  {
    id: 91,
    title: "Late Night Drive",
    artist: "Saib",
    album: "Around The World",
    duration: "2:40",
    durationSec: 160,
    color: "linear-gradient(135deg, #3a1c71, #d76d77)",
    emoji: "🚗",
    genre: "Bossa Lo-Fi",
    category: "chill",
    plays: "21.3M",
    youtubeId: "TYSrG2PMRx8",
  },
  {
    id: 92,
    title: "Weightless",
    artist: "Marconi Union",
    album: "Ambient Transmissions",
    duration: "8:05",
    durationSec: 485,
    color: "linear-gradient(135deg, #1f4037, #99f2c8)",
    emoji: "🫧",
    genre: "Ambient",
    category: "chill",
    plays: "35.8M",
    youtubeId: "UfcAVejslrU",
  },
  {
    id: 93,
    title: "Clair de Lune",
    artist: "Claude Debussy",
    album: "Suite Bergamasque",
    duration: "5:03",
    durationSec: 303,
    color: "linear-gradient(135deg, #2b5876, #4e4376)",
    emoji: "🌙",
    genre: "Classical",
    category: "chill",
    plays: "58.2M",
    youtubeId: "X-Xxqt6Xdio",
    favorite: true,
  },
  {
    id: 94,
    title: "Gymnopédie No. 1",
    artist: "Erik Satie",
    album: "Trois Gymnopédies",
    duration: "3:15",
    durationSec: 195,
    color: "linear-gradient(135deg, #e0eafc, #cfdef3)",
    emoji: "🎹",
    genre: "Classical / Minimalist",
    category: "chill",
    plays: "44.9M",
    youtubeId: "EaTjt_iIs2s",
  },
  {
    id: 95,
    title: "River Flows in You",
    artist: "Yiruma",
    album: "First Love",
    duration: "3:38",
    durationSec: 218,
    color: "linear-gradient(135deg, #89f7fe, #66a6ff)",
    emoji: "🌊",
    genre: "New Age / Piano",
    category: "chill",
    plays: "73.4M",
    youtubeId: "92IlKBhKbWM",
    favorite: true,
  },
  {
    id: 96,
    title: "Kiss the Rain",
    artist: "Yiruma",
    album: "From The Yellow Room",
    duration: "4:16",
    durationSec: 256,
    color: "linear-gradient(135deg, #4facfe, #00f2fe)",
    emoji: "🌧️",
    genre: "New Age / Piano",
    category: "chill",
    plays: "51.0M",
    youtubeId: "I0et_hDtfxY",
  },
  {
    id: 97,
    title: "Experience",
    artist: "Ludovico Einaudi",
    album: "In a Time Lapse",
    duration: "5:15",
    durationSec: 315,
    color: "linear-gradient(135deg, #434343, #000000)",
    emoji: "🎻",
    genre: "Neo-Classical",
    category: "chill",
    plays: "62.7M",
    youtubeId: "1e9B31FLT-s",
    favorite: true,
  },
  {
    id: 98,
    title: "Nuvole Bianche",
    artist: "Ludovico Einaudi",
    album: "Una Mattina",
    duration: "5:57",
    durationSec: 357,
    color: "linear-gradient(135deg, #abbaab, #ffffff)",
    emoji: "☁️",
    genre: "Neo-Classical",
    category: "chill",
    plays: "69.1M",
    youtubeId: "CQ8zglIXZi8",
  },
  {
    id: 99,
    title: "Time",
    artist: "Hans Zimmer",
    album: "Inception (OST)",
    duration: "4:35",
    durationSec: 275,
    color: "linear-gradient(135deg, #141e30, #243b55)",
    emoji: "⏳",
    genre: "Cinematic",
    category: "chill",
    plays: "85.3M",
    youtubeId: "c56t7upa8Bk",
    favorite: true,
  },
  {
    id: 100,
    title: "Cornfield Chase",
    artist: "Hans Zimmer",
    album: "Interstellar (OST)",
    duration: "2:06",
    durationSec: 126,
    color: "linear-gradient(135deg, #09090e, #291147)",
    emoji: "🚀",
    genre: "Cinematic",
    category: "chill",
    plays: "91.2M",
    youtubeId: "JuSsvM8B4Jc",
    favorite: true,
  },
];
